#!/usr/bin/env bash

# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

# Setup monitor
export MONITOR_BASE=eDP-1
export MONITOR_EXTRA=DP-1

# Launch
polybar base &
polybar extra &

echo "Bars launched..."
